<DIV class=main_left_s></DIV>
<DIV class=title><SPAN class=more><a href="{dede:field name='typeurl'/}" target="_blank">more</a></SPAN><a href="{dede:field name='typeurl'/}"><span style="font-size:14px;">{dede:field name='typename'/}</span></a></DIV>
<DIV class=box>
<DIV class=fm_box_right>
<UL>
    {dede:arclist titlelen='60' row='8'}
<li><span><em class="newDate">[field:pubdate function="MyDate('m-d',@me)"/]</em></span>[<a class="green" href="[field:typeurl /]">[field:typename /]</a>]<a href="[field:arcurl /]">[field:title /]</a></li>
  {/dede:arclist}
</UL></DIV> 
<DIV class=clear></DIV></DIV>
<DIV class=main_left_x></DIV>